language: csharp

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      dotnet: 1.0.1
      mono: none
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.1
      mono: none

branches:
  only:
    - master
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi
script:
  - if [ -n "${DOTNETCORE}" ]; then dotnet restore "src\FileUploadAspNetCore" && dotnet build "src\FileUploadAspNetCore"; fi
