version: '1.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
branches:
  only:
    - master
init:
  - git config --global core.autocrlf true
  - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\FileUploadAspNetCore" -c %CONFIGURATION% --version-suffix %LABEL%
after_build:
- dotnet publish "src\FileUploadAspNetCore" -c %CONFIGURATION% --version-suffix %LABEL% -o ../../release
test: off
environment:
  access_token:
    secure: gPLaCoISbGAJCbPE7vGAEkRMtiDH17XvyEzweZlp8pt6zjsOCTMZlmd1296tzgcz
  git_email:
    secure: dCEJcIf4jXWH0PrQcRaXuvvT8l7C5GwosxOsmi0c564=
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "$($env:git_email)"
  - git config --global user.name "codeyu"
  - git config --global core.autocrlf true
  - git checkout master
  - git add .
  - git commit -m "ci deploy"
  - git status
  - git push origin master:release -f